# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: ecommerce-deployment
#   labels:
#     app: ecommerce
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: ecommerce
#   template:
#     metadata:
#       labels:
#         app: ecommerce
#     spec:
#       containers:
#         - name: ecommerce-container
#           image: nexus.imcc.com:8082/ecommerce-web:latest
#           ports:
#             - containerPort: 8000
#           env:
#             - name: DJANGO_SETTINGS_MODULE
#               value: "ecommerce.settings"



apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-web-deployment
  labels:
    app: ecommerce-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-web
  template:
    metadata:
      labels:
        app: ecommerce-web
    spec:
      containers:
        - name: ecommerce-web
          image: localhost:8082/ecommerce-web:latest
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
