# apiVersion: v1
# kind: Service
# metadata:
#   name: ecommerce-service
# spec:
#   selector:
#     app: ecommerce
#   type: NodePort
#   ports:
#     - protocol: TCP
#       port: 8000
#       targetPort: 8000
#       nodePort: 30008



apiVersion: v1
kind: Service
metadata:
  name: ecommerce-web-service
spec:
  type: NodePort
  selector:
    app: ecommerce-web
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
